Countdown added
felicity-iiith/felicity18-website pull request #12
Opened 2017-09-21 11:49 UTC by sayak119

#6 Countdown timer added

2017-09-22 08:36 UTC, meghprkh requested changes

2017-09-22 08:36 UTC, meghprkh commented on static/css/webslides.css
> +
Make this more specific as in specify class names or ids for which you want these to apply

2017-09-22 22:18 UTC, acashmkj commented on static/css/webslides.css
> +
sir made the changes

2017-09-23 20:15 UTC, meghprkh approved these changes

2017-09-23 20:20 UTC, meghprkh commented
Merged via 1bc7498

2017-09-23 20:20 UTC, closed without merging